name: datanavigator
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy<2
  - pandas
  - matplotlib
  - portion
  - ffmpeg-python
  - pytables
  - tqdm
  - pip:
    - opencv-python
    - pysampled
    - decord
