name: datanavigator
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10,<=3.13
  - pip
  - numpy
  - pandas
  - matplotlib
  - portion
  - ffmpeg-python
  - pytables>=3.10
  - tqdm
  - pytest
  - pip:
    - opencv-python
    - pysampled
    - av
