name: dev-datanavigator
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - numpy
  - matplotlib
  - opencv
  - portion
  - ffmpeg-python
  - pip:
    - opencv-contrib-python
    - pysampled
    - decord
