"""Unit tests for the decord-compatible VideoReader shim (PyAV+TOC backend).

Generates a small synthetic clip per test via ffmpeg's ``testsrc`` filter
and exercises every shim entry point that downstream call sites depend
on. The parity-harness regression gate
(``tests/decord_pyav_parity/run_parity.py``) covers byte-exact frame
equivalence against the ffmpeg-CLI oracle; this module covers API
shape only.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import numpy as np
import pytest


FPS = 24
DURATION_S = 1
N_FRAMES = FPS * DURATION_S  # 24


def _have_ffmpeg() -> bool:
    return shutil.which("ffmpeg") is not None


pytestmark = pytest.mark.skipif(not _have_ffmpeg(), reason="ffmpeg not on PATH")


@pytest.fixture(scope="module")
def synthetic_clip(tmp_path_factory) -> Path:
    """A tiny 24fps, 1s, 64x48 H.264 clip generated by ffmpeg's testsrc."""
    out = tmp_path_factory.mktemp("video_reader") / "testsrc.mp4"
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc=duration={DURATION_S}:size=64x48:rate={FPS}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-g", "12",
        str(out),
    ]
    subprocess.run(cmd, check=True)
    assert out.exists() and out.stat().st_size > 0
    return out


def test_indexing_returns_rgb_ndarray(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    arr = vr[0].asnumpy()
    assert isinstance(arr, np.ndarray)
    assert arr.dtype == np.uint8
    assert arr.shape == (48, 64, 3)


def test_negative_index(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    last = vr[-1].asnumpy()
    assert last.shape == (48, 64, 3)


def test_slice_returns_stacked_batch(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    batch = vr[1:4].asnumpy()
    assert batch.shape == (3, 48, 64, 3)
    assert batch.dtype == np.uint8


def test_get_batch_returns_stacked_batch(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    batch = vr.get_batch([0, 5, 9]).asnumpy()
    assert batch.shape == (3, 48, 64, 3)


def test_len_matches_expected(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    assert len(vr) == N_FRAMES


def test_iteration_yields_all_frames(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    frames = list(vr)
    assert len(frames) == N_FRAMES
    assert frames[0].asnumpy().shape == (48, 64, 3)


def test_get_avg_fps(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    fps = vr.get_avg_fps()
    assert isinstance(fps, float)
    assert abs(fps - FPS) < 0.1


def test_cpu_sentinel_constructs_and_is_accepted(synthetic_clip):
    from datanavigator import VideoReader, cpu

    ctx = cpu(0)
    assert ctx is not None
    vr = VideoReader(str(synthetic_clip), ctx=ctx, width=-1, height=-1, num_threads=0, fault_tol=-1)
    assert len(vr) == N_FRAMES


def test_video_subclass_constructs(synthetic_clip):
    from datanavigator import Video

    v = Video(str(synthetic_clip))
    assert len(v) == N_FRAMES
    assert v.name == "testsrc"


def test_videoreader_exposes_fname_and_name(synthetic_clip):
    """1.5.0a2: base VideoReader carries ``fname`` + ``name`` so callers
    that previously required the ``utils.Video`` subclass (notably
    ``dustrack.VideoAnnotation``) can be handed a plain reader. Lets
    DUSTrack share a single open reader across every annotation layer
    of a session instead of opening the file once per layer.
    """
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    assert vr.fname == str(synthetic_clip)
    assert vr.name == "testsrc"


def test_videoreader_filehandle_fname_resolves_to_path(synthetic_clip):
    """File-handle inputs still produce a string path on ``fname``."""
    from datanavigator import VideoReader

    with open(str(synthetic_clip), "rb") as f:
        vr = VideoReader(f)
        assert vr.fname == str(synthetic_clip)
        assert vr.name == "testsrc"


def test_video_gray_uses_rgb_to_gray(synthetic_clip):
    """Regression gate for the 1.3.0 RGB/BGR fix.

    Confirms gray() routes RGB→GRAY (not BGR→GRAY). Verified by
    constructing a synthetic red frame whose luma under BGR→GRAY
    would equal the blue-channel coefficient and under RGB→GRAY
    would equal the red-channel coefficient. We assert against the
    RGB→GRAY expectation.
    """
    from datanavigator import Video
    import cv2 as cv

    v = Video(str(synthetic_clip))
    gray = v.gray(0)
    assert isinstance(gray, np.ndarray)
    assert gray.ndim == 2
    assert gray.dtype == np.uint8
    assert gray.shape == (48, 64)

    # Round-trip: applying the same conversion to the asnumpy()-fetched
    # frame should reproduce gray() exactly. This pins the channel order
    # used inside gray(); any silent revert to COLOR_BGR2GRAY would
    # change the right-hand side and break equality.
    expected = cv.cvtColor(v[0].asnumpy(), cv.COLOR_RGB2GRAY)
    assert np.array_equal(gray, expected)


# ---------- pix_fmt='gray' opt-in + auto-detect ----------

@pytest.fixture(scope="module")
def mono_clip(tmp_path_factory) -> Path:
    """Tiny h265 monochrome (pix_fmt=gray) clip for the gray-decode path."""
    out = tmp_path_factory.mktemp("video_reader_mono") / "testsrc_mono.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", f"testsrc=duration={DURATION_S}:size=64x48:rate={FPS}",
            "-c:v", "libx265", "-pix_fmt", "gray", "-x265-params", "log-level=none",
            str(out),
        ],
        check=True,
    )
    return out


def test_pix_fmt_default_yuv420p_source_is_rgb24(synthetic_clip):
    """Auto-detect on a color source (yuv420p) selects rgb24 -- the
    historical behaviour; existing call sites must not regress."""
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    assert vr.pix_fmt == "rgb24"
    arr = vr[0].asnumpy()
    assert arr.shape == (48, 64, 3)


def test_pix_fmt_default_mono_source_is_gray(mono_clip):
    """Auto-detect on a monochrome source (pix_fmt=gray) selects the
    gray decode path: vr[i].asnumpy() returns (H, W) directly."""
    from datanavigator import VideoReader

    vr = VideoReader(str(mono_clip))
    assert vr.pix_fmt == "gray"
    arr = vr[0].asnumpy()
    assert arr.shape == (48, 64)
    assert arr.dtype == np.uint8


def test_pix_fmt_explicit_gray_on_color_source(synthetic_clip):
    """Explicit ``pix_fmt='gray'`` forces gray decode on a yuv420p
    source. PyAV's swscale extracts Y (skipping chroma); shape is (H, W)."""
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip), pix_fmt="gray")
    assert vr.pix_fmt == "gray"
    arr = vr[0].asnumpy()
    assert arr.shape == (48, 64)


def test_pix_fmt_explicit_rgb24_on_mono_source(mono_clip):
    """Explicit ``pix_fmt='rgb24'`` forces rgb24 on a mono source.
    swscale replicates Y across R/G/B; downstream code expecting (H, W, 3)
    keeps working."""
    from datanavigator import VideoReader

    vr = VideoReader(str(mono_clip), pix_fmt="rgb24")
    assert vr.pix_fmt == "rgb24"
    arr = vr[0].asnumpy()
    assert arr.shape == (48, 64, 3)
    # On mono source decoded as rgb24, R == G == B per pixel.
    assert np.array_equal(arr[..., 0], arr[..., 1])
    assert np.array_equal(arr[..., 1], arr[..., 2])


def test_pix_fmt_invalid_raises(synthetic_clip):
    """Anything other than 'rgb24' or 'gray' is a ValueError."""
    from datanavigator import VideoReader

    with pytest.raises(ValueError, match="pix_fmt must be"):
        VideoReader(str(synthetic_clip), pix_fmt="bgr24")


# ---------- TOC sidecar cache ----------

@pytest.fixture
def fresh_clip(tmp_path) -> Path:
    """Per-test clip in its own tmp dir, so the sidecar starts empty."""
    out = tmp_path / "fresh.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", f"testsrc=duration={DURATION_S}:size=64x48:rate={FPS}",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-g", "12",
            str(out),
        ],
        check=True,
    )
    return out


def test_toc_first_open_builds_and_writes_sidecar(fresh_clip, capsys):
    from datanavigator import VideoReader

    sidecar = Path(str(fresh_clip) + ".dnav-toc")
    assert not sidecar.exists()

    vr = VideoReader(str(fresh_clip))
    assert len(vr) == N_FRAMES
    captured = capsys.readouterr()
    assert "building TOC" in captured.out
    assert sidecar.exists()


def test_toc_second_open_hits_cache_silently(fresh_clip, capsys):
    from datanavigator import VideoReader

    VideoReader(str(fresh_clip))  # warm
    capsys.readouterr()  # drain
    VideoReader(str(fresh_clip))
    captured = capsys.readouterr()
    assert "building TOC" not in captured.out


def test_toc_invalidates_on_mtime_change(fresh_clip, capsys):
    from datanavigator import VideoReader

    VideoReader(str(fresh_clip))  # warm
    capsys.readouterr()

    st = fresh_clip.stat()
    # Bump mtime by 2 seconds (FAT resolution-safe).
    os_path = str(fresh_clip)
    new_mtime = st.st_mtime + 2.0
    import os as _os
    _os.utime(os_path, (st.st_atime, new_mtime))

    VideoReader(os_path)
    captured = capsys.readouterr()
    assert "building TOC" in captured.out


def test_toc_invalidates_on_content_change_same_size(fresh_clip, tmp_path, capsys):
    """Two clips of identical size but different content must not alias."""
    from datanavigator import VideoReader

    # Materialise a second clip with different content but matched size.
    alt = tmp_path / "alt.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", f"smptebars=duration={DURATION_S}:size=64x48:rate={FPS}",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-g", "12",
            str(alt),
        ],
        check=True,
    )

    # Warm fresh_clip's cache, then overwrite the file with alt's bytes
    # while preserving mtime (so only the head/tail SHA can detect the change).
    VideoReader(str(fresh_clip))
    capsys.readouterr()
    original_mtime = fresh_clip.stat().st_mtime

    import shutil as _shutil
    _shutil.copyfile(alt, fresh_clip)
    import os as _os
    _os.utime(fresh_clip, (original_mtime, original_mtime))

    VideoReader(str(fresh_clip))
    captured = capsys.readouterr()
    assert "building TOC" in captured.out


def test_toc_corrupted_sidecar_triggers_rebuild(fresh_clip, capsys):
    from datanavigator import VideoReader

    VideoReader(str(fresh_clip))
    capsys.readouterr()

    sidecar = Path(str(fresh_clip) + ".dnav-toc")
    sidecar.write_text("{not valid json")

    VideoReader(str(fresh_clip))
    captured = capsys.readouterr()
    assert "building TOC" in captured.out
    # Sidecar should be replaced with valid JSON at the current schema version
    import json as _json
    from datanavigator.video_reader import _SIDECAR_SCHEMA_VERSION
    assert _json.loads(sidecar.read_text())["schema_version"] == _SIDECAR_SCHEMA_VERSION


def test_get_frame_timestamp_shape_and_monotonicity(fresh_clip, capsys):
    """decord parity: (N, 2) array of [start, end] in seconds, monotonic."""
    from datanavigator import VideoReader

    vr = VideoReader(str(fresh_clip))
    capsys.readouterr()  # drain "building TOC..." from first open
    ts = vr.get_frame_timestamp(range(len(vr)))

    assert ts.shape == (N_FRAMES, 2)
    assert ts.dtype == np.float64
    # First frame starts at 0; ends ~= 1/fps
    assert ts[0, 0] == pytest.approx(0.0, abs=1e-6)
    assert ts[0, 1] > 0
    # Monotonic non-decreasing start times
    assert np.all(np.diff(ts[:, 0]) >= 0)
    # Last frame's end time is close to clip duration (1.0s)
    assert ts[-1, 1] == pytest.approx(DURATION_S, abs=0.1)


def test_get_frame_timestamp_centroid_matches_tobii_pattern(fresh_clip, capsys):
    """Pin tobii.py:243's `.get_frame_timestamp(range(len(vr))).mean(-1)`
    usage: centroids should be monotonic and roughly evenly spaced for CFR."""
    from datanavigator import VideoReader

    vr = VideoReader(str(fresh_clip))
    capsys.readouterr()
    centroids = vr.get_frame_timestamp(range(len(vr))).mean(-1)

    assert centroids.shape == (N_FRAMES,)
    assert np.all(np.diff(centroids) > 0)
    # CFR clip: deltas should cluster tightly around 1/fps.
    deltas = np.diff(centroids)
    assert deltas.std() < (1.0 / FPS) * 0.5


def test_v2_sidecar_persists_timestamps(fresh_clip, capsys):
    """First open builds v2 sidecar; second open hits cache and the
    timestamps come straight from disk (no rebuild announcement)."""
    from datanavigator import VideoReader
    import json as _json

    VideoReader(str(fresh_clip))  # warm
    capsys.readouterr()

    sidecar = Path(str(fresh_clip) + ".dnav-toc")
    data = _json.loads(sidecar.read_text())
    assert data["schema_version"] == 2
    assert "timestamps" in data
    assert "frame_pts" in data["timestamps"]
    assert "frame_durations" in data["timestamps"]
    assert len(data["timestamps"]["frame_pts"]) == N_FRAMES
    assert "time_base" in data
    assert {"num", "den"}.issubset(data["time_base"])

    vr2 = VideoReader(str(fresh_clip))
    captured = capsys.readouterr()
    assert "building TOC" not in captured.out
    assert "indexing frame timestamps" not in captured.out
    # And get_frame_timestamp works without triggering a build
    ts = vr2.get_frame_timestamp([0, 5, 10])
    assert ts.shape == (3, 2)
    captured = capsys.readouterr()
    assert "indexing frame timestamps" not in captured.out


def test_v1_sidecar_lazy_upgrades_on_get_frame_timestamp(fresh_clip, capsys):
    """v1 sidecar (legacy) keeps video reading working; first
    get_frame_timestamp() call lazily builds + upgrades the sidecar to v2."""
    from datanavigator import VideoReader
    from datanavigator import video_reader as _vr
    import json as _json

    # Build a v1 sidecar by hand using the current key.
    key = _vr._cache_key(str(fresh_clip))
    # Borrow the eager build to get a valid TOC, then re-write as v1.
    toc, _ts, _tb = _vr._build_toc_and_timestamps(str(fresh_clip))
    sidecar = Path(str(fresh_clip) + ".dnav-toc")
    sidecar.write_text(_json.dumps({
        "schema_version": 1,
        "key": key,
        "toc": {"lengths": toc["lengths"], "ts": toc["ts"]},
    }))

    # Opening reads v1 silently (no "building" line).
    vr = VideoReader(str(fresh_clip))
    captured = capsys.readouterr()
    assert "building TOC" not in captured.out
    assert "indexing frame timestamps" not in captured.out
    assert len(vr) == N_FRAMES

    # First get_frame_timestamp triggers the lazy build + sidecar upgrade.
    ts = vr.get_frame_timestamp(range(len(vr)))
    captured = capsys.readouterr()
    assert "indexing frame timestamps" in captured.out
    assert ts.shape == (N_FRAMES, 2)

    # Sidecar is now v2 with timestamps.
    data = _json.loads(sidecar.read_text())
    assert data["schema_version"] == 2
    assert len(data["timestamps"]["frame_pts"]) == N_FRAMES


def test_precompute_toc_batch_warmup(fresh_clip, tmp_path, capsys):
    from datanavigator import VideoReader, precompute_toc

    # A second clip with different content/size.
    alt = tmp_path / "alt2.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-f", "lavfi", "-i", f"testsrc=duration={DURATION_S * 2}:size=64x48:rate={FPS}",
            "-c:v", "libx264", "-pix_fmt", "yuv420p", "-g", "12",
            str(alt),
        ],
        check=True,
    )

    results = precompute_toc([fresh_clip, alt], show_progress=False)
    assert results[str(fresh_clip)] == "built"
    assert results[str(alt)] == "built"
    assert Path(str(fresh_clip) + ".dnav-toc").exists()
    assert Path(str(alt) + ".dnav-toc").exists()

    # Second call sees hits
    results2 = precompute_toc([fresh_clip, alt], show_progress=False)
    assert results2[str(fresh_clip)] == "hit"
    assert results2[str(alt)] == "hit"

    # Subsequent open is silent (cache hit)
    capsys.readouterr()  # drain the precompute build noise (none, show_progress=False)
    VideoReader(str(fresh_clip))
    captured = capsys.readouterr()
    assert "building TOC" not in captured.out
