"""Unit tests for the decord-compatible VideoReader shim (PyAV+TOC backend).

Generates a small synthetic clip per test via ffmpeg's ``testsrc`` filter
and exercises every shim entry point that downstream call sites depend
on. The parity-harness regression gate
(``tests/decord_pyav_parity/run_parity.py``) covers byte-exact frame
equivalence against the ffmpeg-CLI oracle; this module covers API
shape only.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import numpy as np
import pytest


FPS = 24
DURATION_S = 1
N_FRAMES = FPS * DURATION_S  # 24


def _have_ffmpeg() -> bool:
    return shutil.which("ffmpeg") is not None


pytestmark = pytest.mark.skipif(not _have_ffmpeg(), reason="ffmpeg not on PATH")


@pytest.fixture(scope="module")
def synthetic_clip(tmp_path_factory) -> Path:
    """A tiny 24fps, 1s, 64x48 H.264 clip generated by ffmpeg's testsrc."""
    out = tmp_path_factory.mktemp("video_reader") / "testsrc.mp4"
    cmd = [
        "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
        "-f", "lavfi", "-i", f"testsrc=duration={DURATION_S}:size=64x48:rate={FPS}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-g", "12",
        str(out),
    ]
    subprocess.run(cmd, check=True)
    assert out.exists() and out.stat().st_size > 0
    return out


def test_indexing_returns_rgb_ndarray(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    arr = vr[0].asnumpy()
    assert isinstance(arr, np.ndarray)
    assert arr.dtype == np.uint8
    assert arr.shape == (48, 64, 3)


def test_negative_index(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    last = vr[-1].asnumpy()
    assert last.shape == (48, 64, 3)


def test_slice_returns_stacked_batch(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    batch = vr[1:4].asnumpy()
    assert batch.shape == (3, 48, 64, 3)
    assert batch.dtype == np.uint8


def test_get_batch_returns_stacked_batch(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    batch = vr.get_batch([0, 5, 9]).asnumpy()
    assert batch.shape == (3, 48, 64, 3)


def test_len_matches_expected(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    assert len(vr) == N_FRAMES


def test_iteration_yields_all_frames(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    frames = list(vr)
    assert len(frames) == N_FRAMES
    assert frames[0].asnumpy().shape == (48, 64, 3)


def test_get_avg_fps(synthetic_clip):
    from datanavigator import VideoReader

    vr = VideoReader(str(synthetic_clip))
    fps = vr.get_avg_fps()
    assert isinstance(fps, float)
    assert abs(fps - FPS) < 0.1


def test_cpu_sentinel_constructs_and_is_accepted(synthetic_clip):
    from datanavigator import VideoReader, cpu

    ctx = cpu(0)
    assert ctx is not None
    vr = VideoReader(str(synthetic_clip), ctx=ctx, width=-1, height=-1, num_threads=0, fault_tol=-1)
    assert len(vr) == N_FRAMES


def test_video_subclass_constructs(synthetic_clip):
    from datanavigator import Video

    v = Video(str(synthetic_clip))
    assert len(v) == N_FRAMES
    assert v.name == "testsrc"


def test_video_gray_uses_rgb_to_gray(synthetic_clip):
    """Regression gate for the 1.3.0 RGB/BGR fix.

    Confirms gray() routes RGB→GRAY (not BGR→GRAY). Verified by
    constructing a synthetic red frame whose luma under BGR→GRAY
    would equal the blue-channel coefficient and under RGB→GRAY
    would equal the red-channel coefficient. We assert against the
    RGB→GRAY expectation.
    """
    from datanavigator import Video
    import cv2 as cv

    v = Video(str(synthetic_clip))
    gray = v.gray(0)
    assert isinstance(gray, np.ndarray)
    assert gray.ndim == 2
    assert gray.dtype == np.uint8
    assert gray.shape == (48, 64)

    # Round-trip: applying the same conversion to the asnumpy()-fetched
    # frame should reproduce gray() exactly. This pins the channel order
    # used inside gray(); any silent revert to COLOR_BGR2GRAY would
    # change the right-hand side and break equality.
    expected = cv.cvtColor(v[0].asnumpy(), cv.COLOR_RGB2GRAY)
    assert np.array_equal(gray, expected)
